first_project/first_app/urls.py
from django.urls import path
from first_app.views import index,signup

app_name = 'first_app'
urlpatterns = [
    # path('', index, name='index'),
    path(r'login', signup, name='sign_up')

]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from first_app.views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# class User(models.Model):
#     user_name= models.CharField(max_length=264,unique=True)
#     email = models.EmailField(max_length=264, unique=True)
#     password = models.PassField(max)
#     def __str__(self):
#         return self.user_name




class UserProfileInfo(models.Model):

    user=models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
from .models import User

class NewUserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = '__all__'

class UserProfileInfo(forms.ModelForm):
    user = models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.user_name

first_project/first_app/views.py
from django.shortcuts import render
from first_app.models import User
from .forms import NewUserForm
# Create your views here.

def index(request):
    webpages_list = User.objects.all()
    user_dictb = {'user_dict':webpages_list}

    return render(request,'first_app/index.html', context=user_dictb)

def signup(request):

    form=NewUserForm()

    if request.method == "POST":
        form=NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Error fill all')
    return render(request,'first_app/signup.html',{'form':form})

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First_projet</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}"/>
    <link rel="stylesheet" href="{% static "css/first.css" %}"/>
</head>
<body>
<div class="container">
        <div class="jumbotron">

            <h1>Welcome to Home Page</h1>
            <h2>Go to /formpage to fill out the form</h2>

        </div>
    </div>

<a href="{% url 'first_app:sign_up' %}" >Sign Up</a>
<h2>user_dict</h2>


<div class="django">

    {% if user_dict %}
        <table>
            <thead>
                <th>
                    User Name
                </th>
                <th>
                   Email
                </th>
            </thead>

            {% for acc in user_dict %}
            <tr>
                <td>{{ acc.user_name }}</td>
                <td>{{ acc.email }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No records</p>
    {% endif %}


</div>
</body>
</html>

first_project/templates/first_app/signup.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static "bootstrap.css" %}"/>
</head>
<body>
    <div class="container">
        <form method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Sign Up">

        </form>
    </div>
</body>
</html>